# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - 706dev

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://706registry.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_46aa83744fb643479ef7c38b3d40e253 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_6ed574b515a340fa8ddf785108839a69 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: 706registry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_46aa83744fb643479ef7c38b3d40e253 }}/706dev:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: '706dev'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_08b6996033fc4c23836a3d1bbbe44336 }}
        images: '706registry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_46aa83744fb643479ef7c38b3d40e253 }}/706dev:${{ github.sha }}'